MERGE INTO TEAM (ID, NAME, DELETED) VALUES (1, 'Name 1', FALSE);
MERGE INTO TEAM (ID, NAME, DELETED) VALUES (2, 'Name 2', FALSE);
MERGE INTO TEAM (ID, NAME, DELETED) VALUES (3, 'Name 3', FALSE);
MERGE INTO TEAM (ID, NAME, DELETED) VALUES (4, 'Name 4', FALSE);

MERGE INTO ELEMENT (ID, NAME, TEAM_ID, DELETED) VALUES (1, 'Element 1', 1, FALSE);

MERGE INTO ELEMENT (ID, NAME, TEAM_ID, DELETED) VALUES (2, 'Element 2', 2, FALSE);
MERGE INTO ELEMENT (ID, NAME, TEAM_ID, DELETED) VALUES (3, 'Element 3', 2, FALSE);

MERGE INTO ELEMENT (ID, NAME, TEAM_ID, DELETED) VALUES (4, 'Element 4', 3, FALSE);
MERGE INTO ELEMENT (ID, NAME, TEAM_ID, DELETED) VALUES (5, 'Element 5', 3, FALSE);
MERGE INTO ELEMENT (ID, NAME, TEAM_ID, DELETED) VALUES (6, 'Element 6', 3, FALSE);

MERGE INTO ELEMENT (ID, NAME, TEAM_ID, DELETED) VALUES (7, 'Element 7', 4, FALSE);
MERGE INTO ELEMENT (ID, NAME, TEAM_ID, DELETED) VALUES (8, 'Element 8', 4, FALSE);
MERGE INTO ELEMENT (ID, NAME, TEAM_ID, DELETED) VALUES (9, 'Element 9', 4, FALSE);
MERGE INTO ELEMENT (ID, NAME, TEAM_ID, DELETED) VALUES (10, 'Element 10', 4, FALSE);